### ISSUE TITLE
lexer does not support color themes

### ISSUE THREAD

**Issue by Alexey-T** [Ven1310/CudaText_Text_Ruber-ru#3]
```
[map]
Caption=-
Section=-
Section Indent=-
Comment=-
Word Big letters=-
String '=-
String "=-
String `=-
Ru=-
En=-
```

Pls assign some styles instead of '-'. 
My result
```
[comments]
str1={
str2=}
styles_cmt=Comment
styles_str=String

[map]
Caption=IdKeyword
Section=IdVar
Section Indent=Label
Comment=Comment
Word Big letters=Id4
String '=String
String "=String2
String `=String3
Ru=Id2
En=Id
Number=Number
Symbol=Symbol
```

![Screenshot_2023-04-20_11-42-08](https://user-images.githubusercontent.com/4154978/233310728-283be6f1-f05d-4159-85fa-8a324f74931e.png)

**Comment by Ven1310** [comment]
Lexer colors were selected on the dark theme 'Ebony'

**Comment by Alexey-T** [comment]
I see. but lexer must work in all themes, and of course in 'default' theme.

**Comment by Ven1310** [comment]
Ok!

**Comment by Alexey-T** [comment]
I posted the contents of my *.cuda-lexmap file in the 1st post. but feel free to change it.

**Comment by Ven1310** [comment]
yes, I threw it, now I try to make it on a waybill

**Comment by Ven1310** [comment]
make it normal

**Comment by Ven1310** [comment]
And I would still like to leave a file with my colors settings

**Comment by Alexey-T** [comment]
Pls, leave a __copy__ of file with your settings, but normal filename must support all themes.

**Comment by Ven1310** [comment]
Yes, in principle, you can indicate in the description that all colors can be in "no value."

**Comment by Alexey-T** [comment]
They can , but such setting will not support themes.

**Comment by Ven1310** [comment]
Agree. I supplemented the description on the forum. Thanks for support:)
